name: build

on:
  [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Build
      run: |
        pip install nuitka
        nuitka --onefile --enable-plugin=tk-inter --assume-yes-for-downloads conv.py

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: conv.exe